#!/bin/sh
# Generates THIRD_PARTY_NOTICES.md: the licence and notice files of every
# module linked into the chcli binary on any platform (macOS, Linux, Windows),
# plus the Go toolchain's own licence. Run it after changing dependencies.
#
#   scripts/third-party-notices.sh          # rewrite THIRD_PARTY_NOTICES.md
#   scripts/third-party-notices.sh --check  # fail if the file is out of date (CI)
set -eu

cd "$(dirname "$0")/.."
out=THIRD_PARTY_NOTICES.md
tmp=$(mktemp)
trap 'rm -f "$tmp" "$tmp.pkgs" "$tmp.files"' EXIT

# Packages linked into the binary, over every target platform, with the
# module they belong to. Test-only dependencies are not included.
for os in darwin linux windows; do
	GOOS=$os GOARCH=amd64 go list -deps \
		-f '{{if and (not .Standard) .Module (not .Module.Main)}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}|{{.Dir}}{{end}}' \
		./cmd/chcli
done | sort -u > "$tmp.pkgs"

# For each linked package, collect licence and notice files from its own
# directory up to the module root, so that sub-packages with licences of
# their own (brotli/flate, go-jose/json, ...) are covered.
while IFS='|' read -r mod ver moddir dir; do
	d=$dir
	while :; do
		for f in "$d"/LICENSE* "$d"/LICENCE* "$d"/COPYING* "$d"/NOTICE*; do
			[ -f "$f" ] && printf '%s|%s|%s|%s\n' "$mod" "$ver" "$moddir" "$f"
		done
		[ "$d" = "$moddir" ] && break
		d=$(dirname "$d")
	done
done < "$tmp.pkgs" | sort -u > "$tmp.files"

{
	echo '# Third-party notices'
	echo
	echo 'chcli is distributed under the MIT License (see LICENSE). Its binaries also'
	echo 'contain the following software, reproduced here with the notices their'
	echo 'licences require. The list is the union over the macOS, Linux and Windows'
	echo 'builds; some modules are only linked on one of them. It is generated by'
	echo '`scripts/third-party-notices.sh` from the module cache.'
	echo
	echo '## The Go toolchain (runtime and standard library)'
	echo
	echo '```'
	cat "$(go env GOROOT)/LICENSE"
	echo '```'
	prev=
	while IFS='|' read -r mod ver moddir f; do
		if [ "$mod $ver" != "$prev" ]; then
			prev="$mod $ver"
			echo
			echo "## $mod $ver"
		fi
		rel=${f#"$moddir"/}
		echo
		echo "\`$rel\`:"
		echo
		echo '```'
		cat "$f"
		echo '```'
	done < "$tmp.files"
} > "$tmp"

if [ "${1:-}" = --check ]; then
	if diff -u "$out" "$tmp"; then
		echo "$out is up to date"
	else
		echo "$out is out of date; run scripts/third-party-notices.sh" >&2
		exit 1
	fi
else
	mv "$tmp" "$out"
	echo "wrote $out ($(grep -c '^## ' "$out") sections)"
fi
